Adds missing standard include <memory> for std::shared_ptr<>.
Fixes build breakage from upstream LLVM change:
https://github.com/llvm/llvm-project/commit/ffc7380ff4808fcc21350a39caf7f34073b41697

frameworks/base/libs/hwui/renderthread/HintSessionWrapper.h:101:41: error: implicit instantiation of undefined template 'std::shared_ptr<android::uirenderer::renderthread::HintSessionWrapper::HintSessionBinding>'
  101 |     std::shared_ptr<HintSessionBinding> mBinding;
      |                                         ^
prebuilts/clang/host/linux-x86/clang-dev/include/c++/v1/__fwd/memory.h:24:28: note: template is declared here
   24 | class _LIBCPP_TEMPLATE_VIS shared_ptr;
      |                            ^

Test: presubmit
Google: 3440745
Change-Id: Icc0f366c6f1e57aa9ede9fe4868f0a66dff2db94
Signed-off-by: Dmitrii <bankersenator@gmail.com>